import Head from 'next/head'
import { ProductCard } from '../../components/ProductCard'
import { useGetProducts } from '../../hooks/useGetProducts'
import { Product } from '../../models/product.model'
import styles from '../../styles/Home.module.css'


export default function Products() {

  const {products} = useGetProducts()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          {products.map((product:Product)=>{
            return (
              <ProductCard {...product} />
            )
          })}
      </main>
    </div>
  )
}
