import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Web development - Diego Vergara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Desarrollador Web</h1>
        <h2>Diego Vergara</h2>
      </main>
    </div>
  )
}
